"""
Django settings for nextnbr project.

Generated by 'django-admin startproject' using Django 1.8.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.conf.global_settings import MEDIA_ROOT
from django.utils import timezone

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
##Added by Mugdha
#BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'vgt7zu$op)pu7d*$oa&-ds@2eq-a&=kpr2rezk@sb)*@i@pau+'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='localhost'
EMAIL_PORT=25
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
FILER_DEBUG=True
ALLOWED_HOSTS = []

import django.contrib.auth
django.contrib.auth.LOGIN_URL = '/'
AUTH_PROFILE_MODULE = 'profileapp.UserProfile'

GEOPOSITION_MAP_OPTIONS = {
    'minZoom': 3,
    'maxZoom': 18,
}

GEOPOSITION_MARKER_OPTIONS = {
    'cursor': 'move'
}


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	'login',
    'profileapp',
    'geoposition',
	'bootstrap3',
	'django_messages',
	'user_messages',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#MEDIA_ROOT ='C:\\Users\\Vasundhara Patil\\Documents\\GitHub\\next\\media'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')
# MEDIA_ROOT='C:\\Users\\Vasundhara Patil\\Desktop\\images'
MEDIA_URL='/media/'
#STATIC_URL='/static/'
STATIC_ROOT=''

ROOT_URLCONF = 'nextnbr.urls'
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'profileapp/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nextnbr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
		'ENGINE' : 'django.db.backends.oracle',
		'NAME' : 'localhost:1521/pdborcl',
		'USER' : 'nextnbr',
		'PASSWORD' : 'Passw0rd',
		#'HOST' : 'localhost',
		#'PORT' : '1521',
	},
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'nbrcache',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE='America/New_York'
# timezone.activate(TIME_ZONE)
# timezone.localtime(timezone.now())
# TIME_ZONE = timezone.get_fixed_timezone(-05.00)
# TIME_ZONE = timezone.get_current_timezone()
# timezone.activate(TIME_ZONE)
TIME_ZONE = 'Americs/New_York'

USE_I18N = True

USE_L10N = True


# USE_TZ = True
#USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
